### ISSUE TITLE
5.0.0-rc1 - big map level mismatch even worse now

### ISSUE THREAD

**Issue by veqtor** [dipdup-net/dipdup-py#262]
**Steps to reproduce:**
Use big map indexes

**What did you expect to happen:**
Not crash with this error very quickly during indexing

**What actually happened:**
Error that happened every now and then before happens very quickly, now even on indexing and not just when something weird happens in real-time

### Environment

* **Python version:** 3.10
* **DipDup version or commit hash:** 5.0.0-rc1
* **Database engine version:** -
* **Hasura version:** -
* **Are you in docker?** No
* **Can you reproduce this issue on `master`?** Not applicable

### Attachment checklist

- [x] General: DipDup logs (~100 lines above stacktrace)
- [ ] General: `config export` output
- [ ] General: `models.py`
- [ ] SQL issues: `schema export` output
- [ ] Hasura issues: Hasura container logs

**Comment by veqtor** [comment]
`INFO     dipdup.index         ziggurats: 1910430: `collections.cclabs1.bm.on_total_supply` handler matched!
INFO     dipdup.index         ziggurats: 1910430: `collections.cclabs1.bm.on_metadata` handler matched!
INFO     dipdup.index         ziggurats: 1910430: `collections.cclabs1.bm.on_ledger_update` handler matched!
INFO     dipdup.index         versum_big_map: 2024519: `versum.identity.bm.on_update_users` handler matched!
Traceback (most recent call last):
  File "/home/veqtor/.local/bin/dipdup", line 8, in <module>
    sys.exit(cli())
  File "/home/veqtor/.local/lib/python3.10/site-packages/asyncclick/core.py", line 1150, in __call__
    return anyio.run(self._main, main, args, kwargs, **({"backend":_anyio_backend} if _anyio_backend is not None else {}))
  File "/home/veqtor/.local/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 56, in run
    return asynclib.run(func, *args, **backend_options)
  File "/home/veqtor/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 233, in run
    return native_run(wrapper(), debug=debug)
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/veqtor/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 228, in wrapper
    return await func(*args)
  File "/home/veqtor/.local/lib/python3.10/site-packages/asyncclick/core.py", line 1153, in _main
    return await main(*args, **kwargs)
  File "/home/veqtor/.local/lib/python3.10/site-packages/asyncclick/core.py", line 1074, in main
    rv = await self.invoke(ctx)
  File "/home/veqtor/.local/lib/python3.10/site-packages/asyncclick/core.py", line 1684, in invoke
    return await _process_result(await sub_ctx.command.invoke(sub_ctx))
  File "/home/veqtor/.local/lib/python3.10/site-packages/asyncclick/core.py", line 1420, in invoke
    return await ctx.invoke(self.callback, **ctx.params)
  File "/home/veqtor/.local/lib/python3.10/site-packages/asyncclick/core.py", line 774, in invoke
    rv = await rv
  File "/home/veqtor/.local/lib/python3.10/site-packages/dipdup/cli.py", line 94, in wrapper
    await fn(*args, **kwargs)
  File "/home/veqtor/.local/lib/python3.10/site-packages/dipdup/cli.py", line 218, in run
    await dipdup.run()
  File "/home/veqtor/.local/lib/python3.10/site-packages/dipdup/dipdup.py", line 377, in run
    await gather(*tasks)
  File "/home/veqtor/.local/lib/python3.10/site-packages/dipdup/dipdup.py", line 86, in run
    await gather(*tasks)
  File "/home/veqtor/.local/lib/python3.10/site-packages/dipdup/dipdup.py", line 114, in _run
    await gather(*tasks)
  File "/home/veqtor/.local/lib/python3.10/site-packages/dipdup/index.py", line 222, in process
    await self._synchronize(sync_level)
  File "/home/veqtor/.local/lib/python3.10/site-packages/dipdup/index.py", line 635, in _synchronize
    await self._synchronize_full(first_level, last_level, cache)
  File "/home/veqtor/.local/lib/python3.10/site-packages/dipdup/index.py", line 659, in _synchronize_full
    await self._process_level_big_maps(big_maps)
  File "/home/veqtor/.local/lib/python3.10/site-packages/dipdup/index.py", line 712, in _process_level_big_maps
    raise RuntimeError(f'Level of big map batch must be higher than index state level: {level} <= {self.state.level}')
RuntimeError: Level of big map batch must be higher than index state level: 1802335 <= 1802339
________________________________________________________________________________

Unexpected error occurred!

Please file a bug report at https://github.com/dipdup-net/dipdup/issues and attach the following:

  * `dipdup.yml` config. Make sure to remove sensitive information.
  * Reasonable amount of logs before the crash.

veqtor@FXK5PG3:/mnt/c/dev/versum/versum-dipdup$`
