### ISSUE TITLE
Messages not dropped from TzKT buffer on rollback

### ISSUE THREAD

**Issue by Karantezsure** [dipdup-net/dipdup-py#329]
**Steps to reproduce:**

**What did you expect to happen:** Not to get Rollback Error

**What actually happened:** Getting the rollback error even by using buffer_size = 2

### Environment

* **Python version:** ^3.10
* **DipDup version or commit hash:** 5.0.4
* **Database engine version:**
* **Hasura version:** v2.0.1
* **Are you in docker?** yes

**Error Message:**
```
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/local/bin/dipdup", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 1150, in __call__
    return anyio.run(self._main, main, args, kwargs, **({"backend":_anyio_backend} if _anyio_backend is not None else {}))
  File "/usr/local/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 56, in run
    return asynclib.run(func, *args, **backend_options)
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 233, in run
    return native_run(wrapper(), debug=debug)
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
    handle._run()
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/site-packages/pysignalr/transport/websocket.py", line 156, in _process
    await self._on_raw_message(raw_message)
  File "/usr/local/lib/python3.10/site-packages/pysignalr/transport/websocket.py", line 208, in _on_raw_message
    await self._on_message(message)
  File "/usr/local/lib/python3.10/site-packages/pysignalr/transport/websocket.py", line 211, in _on_message
    await self._callback(message)
INFO     dipdup.tzkt          tzkt_mainnet: Level 2342009 is not buffered, can't avoid rollback
  File "/usr/local/lib/python3.10/site-packages/pysignalr/client.py", line 149, in _on_message
    await self._on_invocation_message(message)
  File "/usr/local/lib/python3.10/site-packages/pysignalr/client.py", line 172, in _on_invocation_message
    await callback(message.arguments)
  File "/usr/local/lib/python3.10/site-packages/dipdup/datasources/tzkt/datasource.py", line 888, in _on_message
    if not self._buffer.rollback(type_, channel_level, message_level):
  File "/usr/local/lib/python3.10/site-packages/dipdup/datasources/tzkt/datasource.py", line 295, in rollback
    self._logger.info('Rollback requested from %s to %s', type_.value, channel_level, message_level)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/dipdup/utils/__init__.py", line 119, in _log
    self.logger._log(level, msg, args, exc_info, extra, stack_info, stacklevel)
Message: 'tzkt_mainnet: Rollback requested from %s to %s'
Arguments: ('big_map', 2342009, 2342008)
WARNING  dipdup               Datasource `https://api.tzkt.io` rolled back: 2342009 -> 2342008
INFO     dipdup               Checking if single level rollback is possible
INFO     dipdup               Indexes: 3 total, 3 matching, 1 support single level rollback
WARNING  dipdup.context       Reindexing requested: reason `rollback`, action `exception`
INFO     apscheduler.scheduler Scheduler has been shut down
Traceback (most recent call last):
  File "/usr/local/bin/dipdup", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 1150, in __call__
    return anyio.run(self._main, main, args, kwargs, **({"backend":_anyio_backend} if _anyio_backend is not None else {}))
  File "/usr/local/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 56, in run
    return asynclib.run(func, *args, **backend_options)
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 233, in run
    return native_run(wrapper(), debug=debug)
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 228, in wrapper
    return await func(*args)
  File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 1153, in _main
    return await main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 1074, in main
    rv = await self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 1684, in invoke
    return await _process_result(await sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 1420, in invoke
    return await ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 774, in invoke
    rv = await rv
  File "/usr/local/lib/python3.10/site-packages/dipdup/cli.py", line 87, in wrapper
    await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/dipdup/cli.py", line 205, in run
    await dipdup.run()
  File "/usr/local/lib/python3.10/site-packages/dipdup/dipdup.py", line 372, in run
    await gather(*tasks)
  File "/usr/local/lib/python3.10/site-packages/dipdup/dipdup.py", line 525, in _event_wrapper
    await gather(*_tasks)
  File "/usr/local/lib/python3.10/site-packages/dipdup/datasources/tzkt/datasource.py", line 847, in run
    await gather(*tasks)
  File "/usr/local/lib/python3.10/site-packages/dipdup/datasources/tzkt/datasource.py", line 836, in _wrapper
    await ws.run()
  File "/usr/local/lib/python3.10/site-packages/pysignalr/client.py", line 88, in run
    await self._transport.run()
  File "/usr/local/lib/python3.10/site-packages/pysignalr/transport/websocket.py", line 78, in run
    await self._loop()
  File "/usr/local/lib/python3.10/site-packages/pysignalr/transport/websocket.py", line 108, in _loop
    await asyncio.gather(
  File "/usr/local/lib/python3.10/site-packages/pysignalr/transport/websocket.py", line 156, in _process
    await self._on_raw_message(raw_message)
  File "/usr/local/lib/python3.10/site-packages/pysignalr/transport/websocket.py", line 208, in _on_raw_message
    await self._on_message(message)
  File "/usr/local/lib/python3.10/site-packages/pysignalr/transport/websocket.py", line 211, in _on_message
    await self._callback(message)
  File "/usr/local/lib/python3.10/site-packages/pysignalr/client.py", line 149, in _on_message
    await self._on_invocation_message(message)
  File "/usr/local/lib/python3.10/site-packages/pysignalr/client.py", line 172, in _on_invocation_message
    await callback(message.arguments)
  File "/usr/local/lib/python3.10/site-packages/dipdup/datasources/tzkt/datasource.py", line 889, in _on_message
    await self.emit_rollback(channel_level, message_level)
  File "/usr/local/lib/python3.10/site-packages/dipdup/datasources/datasource.py", line 119, in emit_rollback
    await fn(self, from_level, to_level)
  File "/usr/local/lib/python3.10/site-packages/dipdup/dipdup.py", line 299, in _on_rollback
    await self._ctx.fire_hook('on_rollback', datasource=datasource, from_level=from_level, to_level=to_level)
  File "/usr/local/lib/python3.10/site-packages/dipdup/context.py", line 135, in fire_hook
    await self.callbacks.fire_hook(self, name, fmt, wait, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/dipdup/context.py", line 455, in fire_hook
    await _wrapper()
  File "/usr/local/lib/python3.10/site-packages/dipdup/context.py", line 452, in _wrapper
    await hook_config.callback_fn(ctx, *args, **kwargs)
  File "/demo/demo/hooks/on_rollback.py", line 13, in on_rollback
    await ctx.reindex(ReindexingReason.rollback)
  File "/usr/local/lib/python3.10/site-packages/dipdup/context.py", line 191, in reindex
    raise ReindexingRequiredError(schema.reindex, context)
dipdup.exceptions.ReindexingRequiredError: Unable to continue indexing with existing database
________________________________________________________________________________

Reindexing required! Reason: rollback.

You may want to backup database before proceeding. After that perform one of the following actions:

  * Eliminate the cause of reindexing and run `dipdup schema approve`.
  * Drop database and start indexing from scratch with `dipdup schema wipe` command.

See https://docs.dipdup.net/advanced/reindexing for more information.
```

**Comment by droserasprout** [comment]
Confirmed, preparing a fix.
