### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] with tzkt datasource

### ISSUE THREAD

**Issue by vivekascoder** [dipdup-net/dipdup-py#416]
**Steps to reproduce:**
```yml
spec_version: 1.2
package: dex_indexer

database:
  kind: sqlite
  path: db.sqlite3

contracts:
  converter:
    address: KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn
    typename: insta_doja

datasources:
  tzkt_mainnet:
    kind: tzkt
    url: https://api.tzkt.io
  tzkt_jakartanet:
    kind: tzkt
    url: https://api.jakartanet.tzkt.io
    http:
      retry_count: 3

indexes:
  index_convert:
    kind: operation
    datasource: tzkt_jakartanet
    contracts:
      - converter
    handlers:
      - callback: on_convert
        pattern:
          - destination: converter
            entrypoint: convert
```
**What did you expect to happen:**
It should generate files without any errors.

**What actually happened:**
The following error arises.
```
❯❯❯ dipdup init
INFO     dipdup.codegen       Initializing project
INFO     dipdup.codegen       Creating `schemas` directory
INFO     dipdup.codegen       Fetching schemas for contract `KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn`
INFO     dipdup.tzkt          tzkt_jakartanet: Fetching jsonschemas for address `KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn
WARNING  dipdup.http          HTTP request attempt 1/inf failed: Cannot connect to host api.jakartanet.tzkt.io:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]
INFO     dipdup.http          Waiting 1.0 seconds before retry
WARNING  dipdup.http          HTTP request attempt 2/inf failed: Cannot connect to host api.jakartanet.tzkt.io:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]
INFO     dipdup.http          Waiting 1.1 seconds before retry
^CINFO     dipdup.cli           Shutting down
(indexer-0-8wQfKQ-py3.10) 🧟 [vivekascoder@rocket] 📂 ~/work/Insta_DEX/indexer (main) ⚡ 
❯❯❯ dipdup init
INFO     dipdup.codegen       Initializing project
INFO     dipdup.codegen       Creating `schemas` directory
INFO     dipdup.codegen       Fetching schemas for contract `KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn`
INFO     dipdup.tzkt          tzkt_jakartanet: Fetching jsonschemas for address `KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn
WARNING  dipdup.http          HTTP request attempt 1/3 failed: Cannot connect to host api.jakartanet.tzkt.io:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]
INFO     dipdup.http          Waiting 1.0 seconds before retry
WARNING  dipdup.http          HTTP request attempt 2/3 failed: Cannot connect to host api.jakartanet.tzkt.io:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]
INFO     dipdup.http          Waiting 1.1 seconds before retry
WARNING  dipdup.http          HTTP request attempt 3/3 failed: Cannot connect to host api.jakartanet.tzkt.io:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]
INFO     dipdup.http          Waiting 1.2100000000000002 seconds before retry
Traceback (most recent call last):
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1119, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/bin/dipdup", line 8, in <module>
    sys.exit(cli())
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/lib/python3.10/site-packages/asyncclick/core.py", line 1157, in __call__
    return anyio.run(self._main, main, args, kwargs, **opts)
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/lib/python3.10/site-packages/asyncclick/core.py", line 1160, in _main
    return await main(*args, **kwargs)
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/lib/python3.10/site-packages/asyncclick/core.py", line 1076, in main
    rv = await self.invoke(ctx)
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/lib/python3.10/site-packages/asyncclick/core.py", line 1687, in invoke
    return await _process_result(await sub_ctx.command.invoke(sub_ctx))
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/lib/python3.10/site-packages/asyncclick/core.py", line 1434, in invoke
    return await ctx.invoke(self.callback, **ctx.params)
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/lib/python3.10/site-packages/asyncclick/core.py", line 780, in invoke
    rv = await rv
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/lib/python3.10/site-packages/dipdup/cli.py", line 96, in wrapper
    await fn(*args, **kwargs)
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/lib/python3.10/site-packages/dipdup/cli.py", line 296, in init
    await dipdup.init(overwrite_types, keep_schemas)
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/lib/python3.10/site-packages/dipdup/dipdup.py", line 389, in init
    await self._codegen.init(overwrite_types, keep_schemas)
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/lib/python3.10/site-packages/dipdup/codegen.py", line 101, in init
    await self.fetch_schemas()
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/lib/python3.10/site-packages/dipdup/codegen.py", line 156, in fetch_schemas
    contract_schemas = await self._get_schema(index_config.datasource_config, contract_config, originated)
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/lib/python3.10/site-packages/dipdup/codegen.py", line 336, in _get_schema
    address_schemas_json = await datasource.get_jsonschemas(address)
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/lib/python3.10/site-packages/dipdup/datasources/tzkt/datasource.py", line 473, in get_jsonschemas
    return await self.request(
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/lib/python3.10/site-packages/dipdup/http.py", line 59, in request
    return await self._http.request(method, url, cache, weight, **kwargs)
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/lib/python3.10/site-packages/dipdup/http.py", line 212, in request
    return await self._retry_request(method, url, weight, **kwargs)
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/lib/python3.10/site-packages/dipdup/http.py", line 136, in _retry_request
    raise e
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/lib/python3.10/site-packages/dipdup/http.py", line 128, in _retry_request
    return await self._request(
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/lib/python3.10/site-packages/dipdup/http.py", line 177, in _request
    async with self._session.request(
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/Users/vivekascoder/Library/Caches/pypoetry/virtualenvs/indexer-0-8wQfKQ-py3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.jakartanet.tzkt.io:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]
________________________________________________________________________________

An unexpected error has occurred!

Please file a bug report at https://github.com/dipdup-net/dipdup/issues
```

### Environment

* **Python version:** 3.10.5
* **DipDup version or commit hash:** dipdup, version 5.2.2
* **Database engine version:** sqlite

**Comment by droserasprout** [comment]
Hi! I suspect you're using the wrong contract address/datasource pair.

Jakarta API: https://api.jakartanet.tzkt.io/v1/contracts/KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn/interface
Mainnet API: https://api.tzkt.io/v1/contracts/KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn/interface

An error message is very misleading tho.

```text
➜  ~ curl -v https://api.jakartanet.tzkt.io/v1/contracts/KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn/interface
*   Trying 138.201.85.156:443...
* Connected to api.jakartanet.tzkt.io (138.201.85.156) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=api.jakartanet.tzkt.io
*  start date: Jun 23 09:32:52 2022 GMT
*  expire date: Sep 21 09:32:51 2022 GMT
*  subjectAltName: host "api.jakartanet.tzkt.io" matched cert's "api.jakartanet.tzkt.io"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* h2h3 [:method: GET]
* h2h3 [:path: /v1/contracts/KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn/interface]
* h2h3 [:scheme: https]
* h2h3 [:authority: api.jakartanet.tzkt.io]
* h2h3 [user-agent: curl/7.84.0]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x55c490fd2d30)
> GET /v1/contracts/KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn/interface HTTP/2
> Host: api.jakartanet.tzkt.io
> user-agent: curl/7.84.0
> accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 204 
< server: nginx
< date: Thu, 07 Jul 2022 13:24:34 GMT
< tzkt-version: 1.9.1.0
< tzkt-level: 388046
< tzkt-known-level: 388046
< tzkt-synced-at: 2022-07-07T13:24:32Z
< access-control-allow-origin: *
< 
* Connection #0 to host api.jakartanet.tzkt.io left intact
```

**Comment by vivekascoder** [comment]
```
WARNING  dipdup.http          HTTP request attempt 1/inf failed: Cannot connect to host api.tzkt.io:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]
```
The issue seems to be arising from the SSL verification.

**Comment by droserasprout** [comment]
Do you have [ca-certificates](https://repology.org/project/ca-certificates/versions) package installed?

**Comment by vivekascoder** [comment]
IG it is
<img width="679" alt="image" src="https://user-images.githubusercontent.com/54495208/177815294-cd654aea-4681-435c-8a3c-23c68841e3c6.png">

**Comment by droserasprout** [comment]
Try `curl -v https://api.jakartanet.tzkt.io/v1/contracts/KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn/interface`. Maybe there will be some hints.

**Comment by vivekascoder** [comment]
I can't find anything helpful with it.
```
* Connected to api.jakartanet.tzkt.io (138.201.85.156) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [236 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [102 bytes data]
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [4036 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [300 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [37 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=api.jakartanet.tzkt.io
*  start date: Jun 23 09:32:52 2022 GMT
*  expire date: Sep 21 09:32:51 2022 GMT
*  subjectAltName: host "api.jakartanet.tzkt.io" matched cert's "api.jakartanet.tzkt.io"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x15c010600)
> GET /v1/contracts/KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn/interface HTTP/2
> Host: api.jakartanet.tzkt.io
> user-agent: curl/7.77.0
> accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 204
< server: nginx
< date: Fri, 08 Jul 2022 13:05:52 GMT
< tzkt-version: 1.9.1.0
< tzkt-level: 393610
< tzkt-known-level: 393610
< tzkt-synced-at: 2022-07-08T13:05:51Z
< access-control-allow-origin: *
<
{ [0 bytes data]
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host api.jakartanet.tzkt.io left intact
```

**Comment by droserasprout** [comment]
Ouch, sorry, gave you a wrong url. It should be an existing contract.

`curl -v https://api.jakartanet.tzkt.io/v1/contracts/KT1As89XA889jhbut4CDdMj6iqBzBcAAGK4n/interface`

**Comment by droserasprout** [comment]
It seems like a MacOS-specific issue. @vivekascoder, have you seen this link?

https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate
