### ISSUE TITLE
Batch level is lower than index level

### ISSUE THREAD

**Issue by pravin-d** [dipdup-net/dipdup-py#419]
```
INFO     dipdup.tzkt          tzkt_mainnet: Realtime message received: head, DATA, 2486916 -> 2486917
INFO     apscheduler.scheduler Scheduler has been shut down
Traceback (most recent call last):
File "/usr/local/bin/dipdup", line 5, in 
cli()
File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 1150, in call
return anyio.run(self._main, main, args, kwargs, **({"backend":_anyio_backend} if _anyio_backend is not None else {}))
File "/usr/local/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 56, in run
return asynclib.run(func, *args, **backend_options)
File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 233, in run
return native_run(wrapper(), debug=debug)
File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
return future.result()
File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 228, in wrapper
return await func(*args)
File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 1153, in _main
return await main(*args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 1074, in main
rv = await self.invoke(ctx)
File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 1684, in invoke
return await _process_result(await sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 1420, in invoke
return await ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.10/site-packages/asyncclick/core.py", line 774, in invoke
rv = await rv
File "/home/dipdup/source/src/dipdup/cli.py", line 87, in wrapper
await fn(*args, **kwargs)
File "/home/dipdup/source/src/dipdup/cli.py", line 248, in multiprocess
await dipdup.run()
File "/home/dipdup/source/src/dipdup/dipdup.py", line 462, in run
await gather(*tasks)
File "/home/dipdup/source/src/dipdup/dipdup.py", line 91, in run
await gather(*tasks)
File "/home/dipdup/source/src/dipdup/dipdup.py", line 125, in _run
await gather(*tasks)
File "/home/dipdup/source/src/dipdup/index.py", line 225, in process
await self._process_queue()
File "/home/dipdup/source/src/dipdup/index.py", line 315, in _process_queue
await self._process_level_operations(message)
File "/home/dipdup/source/src/dipdup/index.py", line 378, in _process_level_operations
raise RuntimeError(f'Batch level is lower than index level: {batch_level} < {index_level}')
RuntimeError: Batch level is lower than index level: 2486883 < 2486898\
```

### Environment
Ubuntu - Docker
* **Python version:**
* 3.10
* **DipDup version or commit hash:**
* 5.0.3

**Comment by droserasprout** [comment]
Fixed in 5.1.6. Update DipDup to the latest version, please.

**Comment by droserasprout** [comment]
Duplicate: https://github.com/dipdup-net/dipdup-py/pull/381
